config/routes.rb
Rails.application.routes.draw do
   # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    get 'home/index'
    root to: "home#index"
	resources :images
	get 'index', to: 'index#home'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/image.rb
class Image < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
	before_action :set_image, only: [:edit, :update, :destroy, :show]
	def edit
	end
	def update
		@image.update image_params
		redirect_to @image
	end
	def index
		@images = Image.all
	end

	def new
		@image =Image.new
	end

	def create
		#render plain: params[:image].inspect
		@image = Image.new image_params
		@image.save
		redirect_to @image
	end
	def destroy
		@image.destroy
		redirect_to images_path
	end

	def shows
	end
	def set_image
		@image =Image.find params[:id]
	end	

	private

	def image_params
		params.require(:image).permit(:description)
	end
end

app/controllers/index_controller.rb
class IndexController < ApplicationController
	def home
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/images/_form.html.erb
<%= form_for @image do |f| %>
 <%= f.label :description %><br>
 <%= f.text_field :description %>

 	<%= f.submit %>

<% end %>

app/views/images/_image.html.erb
<%= image.description %>
<%=link_to 'Eliminar', image,method: :delete, data:{confirm: 'sure?'}%>
<%= link_to 'Editar mensaje', edit_image_path(image)%> <br>

app/views/images/edit.html.erb
<p>Editen lo que quieran basuras</p>

<%= render 'form' %>

app/views/images/index.html.erb
<%= render @images %>

app/views/images/new.html.erb
<p>Hola las basuras</p>
<%= render 'form' %>

app/views/images/show.html.erb
<%= @image.description %>

app/views/index/home.html.erb
    <nav class="navbar navbar-personalizada navbar-fixed-top">
      <div class="container">
        <div class="navbar-header pagina-scroll">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">Recycle-click</a>
        </div>
        <div id="navbar" class="collapse navbar-collapse navbar-right navbar-main-collpase">
          <ul class="nav navbar-nav">
            <li class="hidden">
              <a href="#pagina-arriba"></a>
            </li>
            <li class="pagina-scroll">
              <a href="#empresa">Empresa</a>
            </li>
            <li class="pagina-scroll">
              <a href="#servicios">Servicios</a>
            </li>
            <li class="pagina-scroll">
              <a href="#clientes">Clientes</a>
            </li>
            <li class="pagina-scroll">
              <a href="#contacto">Contactanos</a>
            </li>
            <li class="pagina-scroll">
              <a href="#follower">suscribete</a>
            </li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>

    <section class="intro">
      <div class="intro-cuerpo">
        <div class="container">
          <riv class="row">
            <div class="col-md-8 col-md-offset-2">
              
            </div>
          </div>
        </div>
      </div>
    </section>

    <section id="empresa" class="container contenido-seccion">
      <h2 class="text-center">Nuestra Empresa</h2>
      <p class="text-center">Aquí información de la empresa<strong> Recycle Natural</strong> Contenido demo</p>
      <br>
      <div class="row">
        <div class="col-md-4">
          <div class="bloque icono-bloque-izquierdo">
             <div class="icono">
               <i class="fa fa-thumbs-up fa-5x"></i>
             </div>
             <div class="contenido-icono">
               <h3>Profesional</h3>
               <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
               </p>
             </div>
          </div>
        </div>

        <div class="col-md-4">
          <div class="bloque icono-bloque-izquierdo">
             <div class="icono">
               <i class="fa fa-money fa-5x"></i>
             </div>
             <div class="contenido-icono">
               <h3>Bajo Costo</h3>
               <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
               </p>
             </div>
          </div>
        </div>

        <div class="col-md-4">
          <div class="bloque icono-bloque-izquierdo">
             <div class="icono">
               <i class="fa fa-check fa-5x"></i>
             </div>
             <div class="contenido-icono">
               <h3> Informacion actualizada </I></h3>
               <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
               </p>
             </div>
          </div>
        </div>

      </div>

       <div class="row">
        <div class="col-md-4">
          <div class="bloque icono-bloque-izquierdo">
             <div class="icono">
               <i class="fa fa-book fa-5x"></i>
             </div>
             <div class="contenido-icono">
               <h3>Información</h3>
               <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
               </p>
             </div>
          </div>
        </div>

        <div class="col-md-4">
          <div class="bloque icono-bloque-izquierdo">
             <div class="icono">
               <i class="fa fa-users fa-5x"></i>
             </div>
             <div class="contenido-icono">
               <h3>Gran Comunidad</h3>
               <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
               </p>
             </div>
          </div>
        </div>

        <div class="col-md-4">
          <div class="bloque icono-bloque-izquierdo">
             <div class="icono">
               <i class="fa fa-heart fa-5x"></i>
             </div>
             <div class="contenido-icono">
               <h3>Satisfacción Garantizada</h3>
               <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
               </p>
             </div>
          </div>
        </div>

      </div>

    </section>

    <section id="servicios" class="contenido-seccion text-center">
      <div class="seccion-servicios">
        <div class="container">
          <h2>Nuestros Servicios</h2>
          <p class="lead"><strong> Recycle-Click </strong>te ofrecemos una gran experiencia par que recicles con nosotros</p>
          <a href="#contacto" class="btn btn-default btn-lg">Contáctenos</a>
        </div>
      </div>
    </section>



   <section id="clientes" class="contenido-seccion text-center">
      <div class="container">
        <h2>Nuestros Clientes</h2>
        <img src="img/alcaldiamayor.jpg" width="200">
        <img src="img/basura cero.jpg" width="200">
        <img src="img/policia-ambiental.jpg" width="200">
        <img src="img/secretaria del medio ambiente.jpg" width="200">
      </div>
    </section>

    <section id="contacto" class="contenido-seccion text-center">
      <div class="row">
        <div class="col-md-8 col-md-offset-2">
        <h2>Contactanos</h2>
        <p>Nos interesa saber lo que usted piensa, escríbanos a travers del formulario de contacto</p>
        <p>contacto@recycle.com</p>
         <ul class="list-inline">
           <li><a href="" class="btn btn-success btn-lg"><i class="fa fa-facebook fa-fw"></i><span class="network-name">Twitter</span></a></li>
            <li><a href="" class="btn btn-success btn-lg"><i class="fa fa-twitter fa-fw"></i><span class="network-name">Facebook</span></a></li>
            <li><a href="" class="btn btn-success btn-lg"><i class="fa fa-google-plus fa-fw"></i><span class="network-name">Google+</span></a></li>
         </ul> 
        </div>
      </div>
    </section>
    <section id="follower" class="contenido-seccion text-center">
    <h2>Suscribete</h2>
      <form>
        <label for="Nombre">Nombre</label>
        <input type="text" id="Nombre" placeholder="Escribe tu nombre" required>
        <label for="Email">E-mail</label>
        <input type="Email" id="Email" placeholder="Escribe tu E-mail" required>
        <label for="Edad">Edad</label>
        <input type="number" id="Edad" min="0" max="100">
        <label for="fecha">fecha</label>
        <input type="date" id="fecha">
        <input type="submit" value="Enviar datos" id="botonSubmit"> 
      </form> 
      </div>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EntornoLimpio</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	<p class="notice"><%= notice %></p>
 	    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>